### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by davqvist** [dalapo/FactoryTech#18] opened 2017-10-16 17:47 UTC
FactoryTech 1.1.0
Forge 2512
MC 1.12.2

So I planned to include FactoryTech in my upcoming modpack as soon as CT support was going to be released, as this is the case now I playtested it for around 6h. Here is the things I noticed that need to improved in my opinion (Let me know if I should make seperate issues).

1.) Non unified sideness: For automating the repair materials only one side can be used to fed them in which is fair enough. The guide said "back or bottom" so I try to automate the Ore Grinder only to find out that it is the top for this block. It is the bottom for the Metal Cutter but the back for the Woodcutter. Debugging to find out which side it is for each block is very frustrating and time consuming. It would be nice if it would be either unified or there would be a visual representation on the texture that is the same across all blocks to show which side is the side to feed those items in.
2.) Items getting deleted: I had it happen several time that using Stack Movers from one machine to the next deleted the item. I think that happens if the item has no place to go (or if it has a place to go, but is isn't inserted from the correct side, not sure exactly). For example I figured out if I move the Dull Blade to the Grindstone it often got deleted.
3.) Repair items not locked in slots: The repair items in the top right have no locked designated slots. While they get accepted in every slot, it makes automating near impossible if one of the items runs out and the slot gets filled with a second repair item instead, leading to the machine not working anymore.
4.) Shift clicking in GUI: There is an issue already open, but not being able to shift click into the GUI is IMHO not only nice to have, but standard these days that players just expect to work.
5.) Placing and Rotating Blocks: It took me 5 hours of frustration to figure out that the rotation of the blocks on placement is not random but rather determined on if you hold shift when you right click. While some might figure that out faster (and I might have missed an info in the book about that) it is certainly not very intuitive. It is also not a very good way as in the majority of the cases you place the block against an inventory anyway which means you need to hold shift and can't control direction at all. That can be very frustrating as you need to dig holes or do dirt pillars all the time to place, sometimes even move machines to get the direction right. Also that you can't use the wrench to rotate the block after placement doesn't help, The "conveyors" (forgot their actual name sorry) also have the problem of nearly have no indication of direction. I wonder if their texture can be changed to be clearer.

Not sure if I forgot anything. But don't get me wrong, your mod is awesome, love the idea, but those issues in total are really detrimental and I can't include it atm in my pack although I'd really love to. Let me know if you have any more questions regarding those points.

**Comment by DrDarkfire** [comment] 2017-10-16 17:51
I would dare to say, if it is open source, look at Immersive engineering for it's rotational placement of conveyors. Really solid way of displaying which way it is going to face

**Comment by dalapo** [comment] 2017-10-16 18:57
1) The side that each machine accepts parts from is shown in their handbook pages. To your credit, the Drill Grinder page was incorrect - it will be fixed in the next update (releasing very soon).

2) Could not reproduce. Which stack mover are you using, and which side are you inserting into?

3) Would be cumbersome to implement, but I won't rule it out.

4) Done.

5) The Monkey Wrench can rotate anything that doesn't have an inventory.

**Comment by davqvist** [comment] 2017-10-16 21:05
1.) Thanks I will have a look, would have never thought of that.
2.) Better you watch it: https://www.twitch.tv/videos/182661197 at around 2:43:50, happened a couple of times later in different setups as well. If you want I can search the timestamps
3.) The question is how to work around the issue. You need some special trickery from other mods to prevent that unless I am missing something. As the goal of the mod is to automate the production line, this seems like a pretty big deal. If you can tell me a way to workaround, I would love to hear.
4.) Nice, awesome.
5.) Either didn't work for me or I indeed only tested on a block with Inventory. But like the White Stack Mover for example is really tricky to place still.

**Comment by dalapo** [comment] 2017-10-16 22:01
I think I've nailed down why the Stack Mover is doing that - I'll report back after doing a round of tests of a fix.

**Comment by davqvist** [comment] 2017-10-17 05:46
Oh that can be easily solved. Look how I did it: https://github.com/davqvist/CustomAchievements/blob/master/src/main/java/com/davqvist/customachievements/block/BlockTrophy.java#L127

**Comment by davqvist** [comment] 2017-10-17 05:59
Regarding 3.) Can't you use SlotItemHandler instead of Slot? I'm referencing this: https://github.com/dalapo/FactoryTech/blob/master/src/main/java/dalapo/factech/gui/ContainerBasicMachine.java#L42

**Comment by dalapo** [comment] 2017-10-31 03:09
Gonna close this now since I think all of your suggestions I've either implemented or explained why I can't.

**Closed by dalapo** 2017-10-31 03:09 UTC
